### ISSUE TITLE
能否让合并后的根据时间进行排序？

### ISSUE THREAD

**Issue by GuangDai** [fuyufjh/mior#7]
现在的是相当于一个个装入队列里面，作者能提供一个思路或者简单的说一下如何实现排序吗？然后我自己可以去尝试一下。
没写过Rust，不是很理解到底该怎么修改源码才行。

**Comment by fuyufjh** [comment]
感谢反馈！可以实现的，需要在 merge_feeds_data 那里增加一个排序，为此，也要把时间（pubDate）parse出来

**Comment by fuyufjh** [comment]
Done
